branch-defaults:
  default:
    environment: image-fillter-app-dev
    group_suffix: null
deploy:
  artifact: www/Archive.zip
global:
  application_name: image-fillter-app
  branch: null
  default_ec2_keyname: udacity-project-2-dev
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: udacity_2_m
  repository: null
  sc: null
  workspace_type: Application
